### ISSUE TITLE
Yellow background on white text makes it difficult to see error

### ISSUE THREAD

**Issue by mypalvikram** [bdsqqq/vesper-zed#1]
A yellow background on white text makes it hard to see errors. Also, the pop-up menu could use a gray border since it blends in with the background.

<img width="428" alt="Screenshot 2024-05-27 at 7 17 22 AM" src="https://github.com/bdsqqq/vesper-zed/assets/6226652/c638029a-0809-410a-9c2a-6895cfb1a6cb">

**Comment by bdsqqq** [comment]
nice catch, will try to find what token makes that yellow and align it to the other backgrounds.

**Comment by mypalvikram** [comment]
> nice catch, will try to find what token makes that yellow and align it to the other backgrounds.

Thanks! Also that hover/hint menu blends in with the background. Would be nice to add a gray border color. 🙏🏽
